# Generated by Django 4.2.7 on 2023-11-24 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.CharField(max_length=255, verbose_name='Tashkilotni kiriting: ')),
                ('location', models.JSONField(blank=True, null=True, verbose_name='Joylashuv')),
                ('photo', models.ImageField(upload_to='media/todos/', verbose_name='Rasm')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trello.member', verbose_name='Xodimni tanlang: ')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trello.task', verbose_name='Vazifani tanlang: ')),
            ],
            options={
                'verbose_name_plural': 'Работа выполнена',
            },
        ),
    ]
