# Generated by Django 4.2.7 on 2023-11-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0002_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='photo',
            field=models.ImageField(upload_to='todos/', verbose_name='Rasm'),
        ),
    ]
