# Generated by Django 4.2.7 on 2023-12-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0003_alter_todo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='org_id_number',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Tashkilot STIR raqami: '),
        ),
    ]
